version: "3"

services:
  postgres:
    image: postgres:12.2
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/usr/src/app:cached
    depends_on:
      - postgres
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/usr/src/app:cached
      - /usr/src/app/node_modules
    depends_on:
      - backend

volumes:
  postgres:
