# Generated by Django 3.0.5 on 2020-04-28 17:31

from django.db import migrations, models
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='update date')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deletion date')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='slug')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('text', models.TextField(verbose_name='text')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publication date')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects_unsafe', django.db.models.manager.Manager()),
            ],
        ),
    ]
